# Generated by Django 4.0 on 2023-07-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceuilcontact',
            old_name='decryption',
            new_name='detail',
        ),
    ]
