# Generated by Django 4.0 on 2023-07-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0002_rename_decryption_acceuilcontact_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceuilcontact',
            options={'verbose_name': 'AcceuilContact', 'verbose_name_plural': 'AcceuilContact'},
        ),
    ]
