# Generated by Django 4.0 on 2023-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_alter_clientecommerce_decryption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAppWebMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=50, null=True)),
                ('Nom_client', models.CharField(max_length=150)),
                ('Nom_entreprise', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('addresses', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=50, null=True)),
                ('decryption', models.TextField(max_length=1000)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('zone', models.CharField(max_length=50, null=True)),
                ('app1', models.CharField(max_length=50)),
                ('app2', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ClientAppWebMobile',
                'verbose_name_plural': 'ClientAppWebMobile',
            },
        ),
    ]
